### ISSUE TITLE
Connecting to Consensys via a NodeJS client

### ISSUE THREAD

**Issue by maneetgoyal** [ShimmerEngineering/ConsensysGRPCAPI#1]
Hi all,

I am trying to connect to Consenssy via a NodeJS client. Code:

```
import { join } from "path";
import { loadPackageDefinition, credentials } from "@grpc/grpc-js";
import { load } from "@grpc/proto-loader";

export async function setUpGRPCClient() {
  const protoPath = join(__dirname, "./ShimmerGRPCAndOJC.proto");
  const packageDefinition = await load(protoPath, {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true,
  });
  // Ref: https://github.com/grpc/grpc-node/tree/master/packages/proto-loader#example-usage
  const { shimmerGRPC } = loadPackageDefinition(packageDefinition) as unknown as ProtoGrpcType;
  const ShimmerClientConstructor = shimmerGRPC.ShimmerServer;
  const client = new ShimmerClientConstructor("localhost:50051", credentials.createInsecure());
  return client;
}
```

Then firing:

```
grpcClient?.sayHello({ name: "Yay" }, (err, val) => {
            if (err !== null) {
              console.log(err);
            } else {
              console.log(val);
            }
          });
```

Consensys is running in the background. But not able to able connect to it. The above snioppen `sayHello` is erroring out

**Comment by JongChern** [comment]
hi, unfortunately this repository is only a placeholder for future potential grpc capabilities when using Consensys. I apologize for the confusion. I have registered your interest in our backlog.

**Comment by maneetgoyal** [comment]
Hi @JongChern,

Just to confirm, are you suggesting that Consensys cannot be connected to via a GRPC client at the moment?

Is there any other of connecting to Consensys programmatically? Using NdoeJS or other language?

**Comment by JongChern** [comment]
There is no way to connect to Consensys programmatically at the moment.

**Comment by maneetgoyal** [comment]
@JongChern many thanks for the prompt response.

we are building a utility to obtain heartbeat data from Shimmer3 devices. Is this possible programmatically? It seems like Shimmer3 is not a BLE device; we could not connect to it using the Web Bluetooth API

**Comment by JongChern** [comment]
you are correct, it isn't a BLE device, Shimmer3 uses the bluetooth serial port profile. It looks like there might be some support for it https://chromestatus.com/feature/6577673212002304 . Note that the shimmer3 does not provide any heartbeat calculations on the device. An alternative is to use the https://shimmersensing.com/product/verisense-pulse-kit/ which is has a BLE radio

**Comment by maneetgoyal** [comment]
@JongChern does that ble radio work with shimmer3 or do we need to switch to shimmer verisense?

**Comment by JongChern** [comment]
no the verisense ble radio does not work with shimmer3, you will need to switch to using the verisense sensor.

**Comment by maneetgoyal** [comment]
@JongChern we are interested in getting GSR data from shimmer3 programmatically. Does that look technically feasible? Thanks for all the responses

**Comment by JongChern** [comment]
Yes that would be possible. We have APIs available to help you get started. https://shimmersensing.com/wearable-sensor-products/software/
